//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Configuration&gt;
        ///  &lt;LANG&gt;
        ///    &lt;KEY NAME=&quot;BT_save&quot; VALUE=&quot;Save&quot; /&gt;
        ///    &lt;KEY NAME=&quot;BT_close&quot; VALUE=&quot;Close&quot; /&gt;
        ///    &lt;KEY NAME=&quot;BT_cancel&quot; VALUE=&quot;Cancel&quot; /&gt;
        ///    &lt;KEY NAME=&quot;BT_create&quot; VALUE=&quot;Create&quot; /&gt;
        ///    &lt;KEY NAME=&quot;BT_yes&quot; VALUE=&quot;Yes&quot; /&gt;
        ///    &lt;!-- Login form --&gt;
        ///    &lt;KEY NAME=&quot;Form_Text&quot; VALUE=&quot;Login&quot; /&gt;
        ///    &lt;KEY NAME=&quot;LB_User&quot; VALUE=&quot;User:&quot; /&gt;
        ///    &lt;KEY NAME=&quot;LB_pass&quot; VALUE=&quot;Pass:&quot; /&gt;
        ///    &lt;KEY NAME=&quot;BT_Login&quot; VALUE=&quot;Login&quot; /&gt;
        ///    &lt;KEY NAME=&quot;CB_autologin&quot; VALUE= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string eng {
            get {
                return ResourceManager.GetString("eng", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;MIMEtypeList&gt;
        ///  &lt;MIMEtype Name=&quot;application/vnd.hzn-3d-crossword&quot; FileExtension=&quot;.x3d&quot; /&gt;
        ///  &lt;MIMEtype Name=&quot;video/3gpp&quot; FileExtension=&quot;.3gp&quot; /&gt;
        ///  &lt;MIMEtype Name=&quot;video/3gpp2&quot; FileExtension=&quot;.3g2&quot; /&gt;
        ///  &lt;MIMEtype Name=&quot;application/vnd.mseq&quot; FileExtension=&quot;.mseq&quot; /&gt;
        ///  &lt;MIMEtype Name=&quot;application/vnd.3m.post-it-notes&quot; FileExtension=&quot;.pwn&quot; /&gt;
        ///  &lt;MIMEtype Name=&quot;application/vnd.3gpp.pic-bw-large&quot; FileExtension=&quot;.plb&quot; /&gt;
        ///  &lt;MIMEtype Name=&quot;application/vnd.3gpp.pic-bw-s [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string mimetypelist {
            get {
                return ResourceManager.GetString("mimetypelist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Configuration&gt;
        ///  &lt;SETTINGS&gt;
        ///    &lt;KEY NAME=&quot;Admin_user&quot; VALUE=&quot;admin&quot; /&gt;
        ///    &lt;KEY NAME=&quot;Admin_password&quot; VALUE =&quot;21232F297A57A5A743894A0E4A801FC3&quot; /&gt;
        ///    &lt;KEY NAME=&quot;AutoLogin&quot; VALUE=&quot;0&quot;/&gt;
        ///    &lt;KEY NAME=&quot;UI_dll_file&quot; VALUE=&quot;Form.UI.dll&quot;/&gt;
        ///    &lt;KEY NAME=&quot;lang&quot; VALUE=&quot;eng.xml&quot;/&gt;
        ///    &lt;KEY NAME=&quot;DATE_TIME_FORMAT&quot; VALUE=&quot;HH:mm dd/MM/yyyy&quot; /&gt;
        ///
        ///    &lt;KEY NAME=&quot;AutoStartTransfer&quot; VALUE=&quot;1&quot;/&gt;
        ///    &lt;KEY NAME=&quot;ShutdownWhenDone&quot; VALUE=&quot;0&quot;/&gt;
        ///    &lt;KEY NAME=&quot;MaxGroupsDownloa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string SettingDefault {
            get {
                return ResourceManager.GetString("SettingDefault", resourceCulture);
            }
        }
    }
}
